## default uri:http://localhost:8888
spring:
  application:
      name: eureka-provider
  cloud:
    config:
      uri: http://localhost:8888/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
server:
  port: 8080