server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-demo

  cloud:
    config:
      server:
        git:
          uri: https://github.com/leon-fly/spring-cloud-config.git

    inetutils:
      timeout-seconds: 10
