server:
  port: 8000
spring:
  application:
    name: spring-cloud-config-demo

  cloud:
    config:
      server:
        git:
          uri: git@github.com:leon-fly/spring-cloud-config.git

    inetutils:
      timeout-seconds: 10
