server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-demo
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/

