spring:
    redis:
        database: 0
        host: 'www.leonwang.tech'
        password: 'yourpwd'
        pool:
            max-active: 50
            max-idle: 50
            max-wait: 2000
            min-idle: 0
        port: 6379
        timeout: 2000